---
title: 'GSEA of Modules with highest Enrichment in SFARI Genes'
output:
  html_document:
    code_folding: 'hide'
---

```{r load_packages, warning=FALSE, message=FALSE}
#setwd('/afs/inf.ed.ac.uk/user/s17/s1725186/Documents/PhD-Models/FirstPUModel/RMarkdowns')

library(tidyverse) ; library(reshape2) ; library(glue) ; library(plotly) ; library(dendextend)
library(RColorBrewer) ; library(viridis) ; require(gridExtra) ; library(GGally)
library(knitr)
library(biomaRt)
library(clusterProfiler) ; library(ReactomePA) ; library(DOSE)

```


Load preprocessed dataset (preprocessing code in 19_10_14_data_preprocessing.Rmd) and clustering (pipeline in 19_10_21_WGCNA.Rmd)
```{r load_dataset, message=FALSE, warning=FALSE}

# Gandal dataset
load('./../Data/preprocessed_data.RData')
datExpr = datExpr %>% data.frame
DE_info = DE_info %>% data.frame


# GO Neuronal annotations: regex 'neuron' in GO functional annotations and label the genes that make a match as neuronal
GO_annotations = read.csv('./../Data/genes_GO_annotations.csv')
GO_neuronal = GO_annotations %>% filter(grepl('neuron', go_term)) %>% 
              mutate('ID'=as.character(ensembl_gene_id)) %>% 
              dplyr::select(-ensembl_gene_id) %>% distinct(ID) %>%
              mutate('Neuronal'=1)


# SFARI Genes
SFARI_genes = read_csv('./../../../SFARI/Data/SFARI_genes_01-03-2020_w_ensembl_IDs.csv')
SFARI_genes = SFARI_genes[!duplicated(SFARI_genes$ID) & !is.na(SFARI_genes$ID),]


# Clusterings
clusterings = read_csv('./../Data/clusters.csv')


# Update DE_info with SFARI and Neuronal information
genes_info = DE_info %>% mutate('ID'=rownames(.)) %>% left_join(SFARI_genes, by='ID') %>% 
  mutate(`gene-score`=ifelse(is.na(`gene-score`), 'None', `gene-score`)) %>%
  left_join(GO_neuronal, by='ID') %>% left_join(clusterings, by='ID') %>%
  mutate(Neuronal=ifelse(is.na(Neuronal), 0, Neuronal)) %>%
  mutate(gene.score=ifelse(`gene-score`=='None' & Neuronal==1, 'Neuronal', `gene-score`), 
         significant=padj<0.05 & !is.na(padj))


clustering_selected = 'DynamicHybrid'
genes_info$Module = genes_info[,clustering_selected]

dataset = read.csv(paste0('./../Data/dataset_', clustering_selected, '.csv'))
dataset$Module = dataset[,clustering_selected]

# Correct SFARI Scores
dataset$gene.score = genes_info$gene.score

# GSEA Results
load('./../Data/GSEA_bonferroni.RData')


SFARI_colour_hue = function(r) {
  pal = c('#FF7631','#FFB100','#E8E328','#8CC83F','#62CCA6','#59B9C9','#b3b3b3','#808080','gray','#d9d9d9')[r]
}

rm(DE_info, GO_annotations, clusterings, getinfo, mart, dds, GO_neuronal)
```
<br>

## Module-Diagnosis Correlation

```{r, fig.width=10}
plot_data = dataset %>% dplyr::select(Module, MTcor) %>% distinct

ggplotly(plot_data %>% ggplot(aes(reorder(Module, -MTcor), MTcor)) + geom_bar(stat='identity', fill = plot_data$Module) + theme_minimal() + 
         xlab('Modules')+ ylab('Module-Diagnosis Correlation') + geom_hline(yintercept =c(0.9, -0.9), color = 'gray', linetype = 'dashed') + 
         theme(axis.text.x = element_text(angle = 90, hjust = 1)))
```

```{r}
top_modules = plot_data$Module[abs(plot_data$MTcor)>0.9]

cat(paste0('Top modules selected: ', paste(top_modules, collapse=', '),'\n'))
```
<br>

# GSEA Results
<br>

## KEGG
```{r, results = 'asis'}

for(module in top_modules){
  df = enrichment_KEGG[[module]] %>% dplyr::select(ID, Description, setSize, NES, p.adjust, qvalues) %>% arrange(desc(NES)) %>% filter(NES>0)
  if(nrow(df)>0){
    print(kable(df, caption = paste0('Enriched terms for module ', module, ' (MTcor = ', round(dataset$MTcor[dataset$Module==module][1],2),')')))
    cat('\n') 
  } else cat(paste0('\nNo enrichment found for module ',module,'\n'))
}

rm(df)
```
<br>

## Reactome
```{r, results = 'asis'}

for(module in top_modules){
  df = enrichment_Reactome[[module]] %>% dplyr::select(ID, Description, setSize, NES, p.adjust, qvalues) %>% arrange(desc(NES)) %>% filter(NES>0)
  if(nrow(df)>0){
    print(kable(df, caption = paste0('Enriched terms for module ', module, ' (MTcor = ', round(dataset$MTcor[dataset$Module==module][1],2),')')))
    cat('\n') 
  } else cat(paste0('\nNo enrichment found for module ',module,'\n'))
}

rm(df)
```
<br>

## Gene Ontology
```{r, results = 'asis'}

for(module in top_modules){
  df = enrichment_GO[[module]] %>% dplyr::select(ID, Description, setSize, NES, p.adjust, qvalues) %>% arrange(desc(NES)) %>% filter(NES>0)
  if(nrow(df)>0){
    print(kable(df, caption = paste0('Enriched terms for module ', module, ' (MTcor = ', round(dataset$MTcor[dataset$Module==module][1],2),')')))
    cat('\n') 
  } else cat(paste0('\nNo enrichment found for module ',module,'\n'))
}

rm(df)
```
<br>

## Disease Gene Network
```{r, results = 'asis'}

for(module in top_modules){
  df = enrichment_DGN[[module]] %>% dplyr::select(ID, Description, setSize, NES, p.adjust, qvalues) %>% arrange(desc(NES)) %>% filter(NES>0)
  if(nrow(df)>0){
    print(kable(df, caption = paste0('Enriched terms for module ', module, ' (MTcor = ', round(dataset$MTcor[dataset$Module==module][1],2),')')))
    cat('\n') 
  } else cat(paste0('\nNo enrichment found for module ',module,'\n'))
}

rm(df)
```
















